import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — QuantAura',
  description: 'The terms that govern use of QuantAura.',
};

// Companion to /privacy; the YouTube API audit asks for Terms of Service
// documentation. Static server component, no client JS.
export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-24">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-[var(--text-secondary)] mb-10">Last updated: 6 August 2026</p>

      <section className="space-y-6 text-[var(--text-secondary)] leading-relaxed">
        <p>
          These terms govern your use of quantaura.tech and QuantAura&apos;s published
          content, including our YouTube channel. By using the site you agree to
          them.
        </p>

        <h2 className="text-xl font-semibold text-[var(--text-primary)] pt-4">What QuantAura is</h2>
        <p>
          QuantAura is a machine-learning research project. It publishes the
          output of a four-model ensemble that predicts short-term Bitcoin
          market regimes, together with the model&apos;s own historical accuracy —
          including its incorrect calls.
        </p>

        <h2 className="text-xl font-semibold text-[var(--text-primary)] pt-4">Not financial advice</h2>
        <p>
          Nothing on this site or our YouTube channel is financial, investment,
          or trading advice. Signals, confidence scores and backtests are
          statistical research outputs. Our own published measurements show
          these signals have historically not been profitable to trade after
          fees. Cryptocurrency trading involves substantial risk of loss. Any
          decision you make is yours alone.
        </p>

        <h2 className="text-xl font-semibold text-[var(--text-primary)] pt-4">Accounts</h2>
        <p>
          You are responsible for your account credentials and for what happens
          under your account. We may suspend accounts that abuse the service,
          attempt to disrupt it, or violate these terms. You can delete your
          account at any time by contacting us.
        </p>

        <h2 className="text-xl font-semibold text-[var(--text-primary)] pt-4">Subscriptions</h2>
        <p>
          A Premium subscription buys access to the full model output — not a
          recommendation to trade on it and no promise of profit. Billing terms
          are shown at the point of purchase.
        </p>

        <h2 className="text-xl font-semibold text-[var(--text-primary)] pt-4">Content and availability</h2>
        <p>
          Content is provided &quot;as is&quot;, without warranties of accuracy,
          completeness, or availability. Model outputs are generated
          automatically and may be wrong, late, or absent. We may change or
          discontinue any part of the service.
        </p>

        <h2 className="text-xl font-semibold text-[var(--text-primary)] pt-4">YouTube content</h2>
        <p>
          Our YouTube channel is generated by an automated pipeline and its use
          of YouTube is governed by the{' '}
          <a className="text-[var(--accent)] underline" href="https://www.youtube.com/t/terms" target="_blank" rel="noopener noreferrer">
            YouTube Terms of Service
          </a>
          . Our handling of data is described in our{' '}
          <a className="text-[var(--accent)] underline" href="/privacy">Privacy Policy</a>.
        </p>

        <h2 className="text-xl font-semibold text-[var(--text-primary)] pt-4">Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, QuantAura is not liable for
          any losses — including trading losses — arising from use of the site,
          its data, or its published content.
        </p>

        <h2 className="text-xl font-semibold text-[var(--text-primary)] pt-4">Contact</h2>
        <p>
          Questions about these terms:{' '}
          <a className="text-[var(--accent)] underline" href="mailto:khan@quantaura.tech">khan@quantaura.tech</a>.
        </p>
      </section>
    </div>
  );
}
