const express = require('express');
const router = express.Router();

/**
 * The research blog: weekly recap posts + daily prediction posts.
 *
 * Weekly posts are generated by weekly.py (quantaura-youtube repo) from the
 * Sunday graded scoreboard. Daily posts are generated by daily_blogpost.py
 * (same repo) after each day's pipeline run.
 *
 * File layout in the quantaura-youtube repo:
 *   state/blog/index.json              — weekly post index
 *   state/blog/<slug>.json             — weekly post detail
 *   state/blog/daily/index.json        — daily post index
 *   state/blog/daily/<slug>.json       — daily post detail
 *
 * This route merges both indexes and routes individual post lookups to the
 * correct directory. The site never authors content — the blog can never
 * state a number the pipeline didn't verify.
 *
 * Auth: SCOREBOARD_TOKEN (fine-grained PAT, contents:read on the youtube repo).
 * Without it the blog renders its empty state rather than erroring.
 */
const REPO = process.env.SCOREBOARD_REPO || 'ak7256369/quantaura-youtube';

// Posts change at most once a day; 10-minute cache keeps the GitHub relay cold.
const TTL_MS = 10 * 60 * 1000;
const cache = new Map(); // path → { at, data }

// Slugs are pipeline-generated (`bitcoin-model-week-<year>-<ww>` or
// `bitcoin-daily-YYYY-MM-DD`); anything else is not looked up.
const SLUG_RE = /^[a-z0-9-]{1,80}$/;

async function fetchGitHub(path) {
    const token = process.env.SCOREBOARD_TOKEN;
    if (!token) return { pending: true };

    const hit = cache.get(path);
    if (hit && Date.now() - hit.at < TTL_MS) return hit.data;

    try {
        const controller = new AbortController();
        const timer = setTimeout(() => controller.abort(), 10000);
        const ghRes = await fetch(
            `https://api.github.com/repos/${REPO}/contents/${path}`,
            {
                headers: {
                    Authorization: `Bearer ${token}`,
                    Accept: 'application/vnd.github.raw+json',
                    'User-Agent': 'quantaura-api',
                },
                signal: controller.signal,
            },
        );
        clearTimeout(timer);

        if (ghRes.status === 404) return { notFound: true };
        if (!ghRes.ok) {
            console.error(`Blog route: GitHub returned ${ghRes.status} for ${path}`);
            return hit ? hit.data : { pending: true };
        }
        const data = await ghRes.json();
        cache.set(path, { at: Date.now(), data });
        return data;
    } catch (error) {
        console.error('Blog route error:', error.message);
        return hit ? hit.data : { pending: true };
    }
}

/**
 * Merge two post index arrays, sort newest-first.
 * Tags each post with post_type so the frontend can style them differently.
 */
function mergeIndexes(weekly, daily) {
    const weeklyPosts = (weekly?.posts || []).map(p => ({ ...p, post_type: 'weekly' }));
    const dailyPosts = (daily?.posts || []).map(p => ({ ...p, post_type: 'daily' }));
    const merged = [...weeklyPosts, ...dailyPosts];
    merged.sort((a, b) => b.published_at.localeCompare(a.published_at));
    return merged;
}

// GET /api/blog — merged post index (public; it IS the marketing)
router.get('/', async (req, res) => {
    const [weeklyData, dailyData] = await Promise.all([
        fetchGitHub('state/blog/index.json'),
        fetchGitHub('state/blog/daily/index.json'),
    ]);

    // If both are not-found/pending, surface that state to the frontend.
    if (weeklyData.notFound && dailyData.notFound) {
        return res.json({ success: true, data: { pending: true } });
    }
    if (weeklyData.pending && dailyData.pending) {
        return res.json({ success: true, data: { pending: true } });
    }

    const posts = mergeIndexes(
        weeklyData.notFound || weeklyData.pending ? null : weeklyData,
        dailyData.notFound || dailyData.pending ? null : dailyData,
    );

    res.json({ success: true, data: { posts } });
});

// GET /api/blog/:slug — one post (weekly or daily)
router.get('/:slug', async (req, res) => {
    const { slug } = req.params;
    if (!SLUG_RE.test(slug)) {
        return res.status(404).json({ success: false, error: 'Not found' });
    }

    // Daily slugs are `bitcoin-daily-YYYY-MM-DD`; weekly are
    // `bitcoin-model-week-YYYY-WW`. Route to the right directory.
    const isDaily = slug.startsWith('bitcoin-daily-');
    const path = isDaily
        ? `state/blog/daily/${slug}.json`
        : `state/blog/${slug}.json`;

    const data = await fetchGitHub(path);
    if (data.pending) return res.json({ success: true, data: { pending: true } });
    if (data.notFound) return res.status(404).json({ success: false, error: 'Not found' });

    // Tag the post with its type so the frontend can render the correct layout.
    res.json({ success: true, data: { ...data, post_type: isDaily ? 'daily' : 'weekly' } });
});

module.exports = router;
